<a href="https://colab.research.google.com/github/schmelto/machine-learning/blob/main/Deeplearning/introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Numpy


## Import Numpy

Before we can use the full functionality of NumPy, we first have to import the library. With the abbreviation "as" we give numpy a "nickname" and from now on we can write np.some_function () for all functions of Numpy.

In [ ]:
import numpy as np

## Numpy functionalities

### Create a vector

A vector in Numpy is represented as an array. Here, a horizontal vector is a 1-dimensional and a vertical vector is a 2-dimensional vector.

The function `np.array ()` creates this multidimensional numpy array (ndarray).

In [ ]:
vector_row = np.array([1,2,3]) # Horizontaler Vektor (1D)
vector_column = np.array([[1],[2],[3]]) # Vertikaler Vektor (2D und somit n x 1 Matrix)
print(vector_row)
print(vector_column)

[1 2 3]
[[1]
 [2]
 [3]]


### Create a matrix

A matrix is also a multi-dimensional array.

Here, too, this is generated with the `np.array ()` function, whereby the number of nestings (array in an array) represents the dimension of the matrix.

In [ ]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


### Helpful initializations of an array

The arrays can be easily filled with data using a few functions.

Here `np.arrange ()` and `np.linspace ()` offer different approaches to create an array with a specific interval.

In [ ]:
# Values from 0 to 30 (exclusive) with step size 2
range_with_fixed_interval = np.arange(0, 30, 2)
print(f"Vektor with arange:\n{range_with_fixed_interval} \n")

# 9 evenly distributed values between 0 and 4
equally_spaced_range = np.linspace(0, 4, 9)
print(f"Vektor with linspace:\n{equally_spaced_range} \n")

Vektor mit arange:
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28] 

Vektor mit linspace:
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ] 



### Helpful initializations of a matrix

There are also clearly defined functions for creating special matrices.

An identity matrix or a matrix of any size, which consists exclusively of ones or zeros, can be created very easily.

In [ ]:
matrix_id = np.eye(3)           # 3 x 3 identity matrix
matrix_ones = np.ones((3, 2))   # Matrix of ones
matrix_zeros = np.zeros((3, 2)) # Matrix of zeros
print(f"identity matrix:\n{matrix_id} \n")
print(f"Ones matrix:\n{matrix_ones} \n")
print(f"Zeros matrix:\n{matrix_zeros} \n")

Identitätsmatrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Einermatrix:
[[1. 1.]
 [1. 1.]
 [1. 1.]] 

Nullermatrix:
[[0. 0.]
 [0. 0.]
 [0. 0.]] 



#### Access to elements of a multi-dimensional array

Access to the individual elements works as shown below and is probably also known from other programming languages.

Using the :-notation, a certain area of the array can be easily queried by specifying a start and end index.
In the case of the index with negative numbers, the array goes through its values in the reverse order.

In [ ]:
vector = np.array([1,2,3])
matrix = np.array([[1,2,3],[4,5,6]])
print(f"Vektor: {vector}")
print(f"Matrix:\n{matrix}")

# The 3rd element of the vector
print(f"\nThe 3rd element of the vector: {vector[2]}")

# The 2nd element in the 2nd row of the matrix
print(f"\nThe 2nd element in the 2nd row of the matrix: {matrix[1,1]}")

# All elements up to and including the 2nd element
print(f"\nAll elements up to and including the 2nd element of the vector: {vector[:2]}")

# Everything from the 3rd element
print(f"\nEverything from the 3rd element of the vector: {vector[3:]}")

# All elements of the vector
print(f"\nAll elements of the vector: {vector[:]}")

# The last element (same result as vector [len (vector) -1])
print(f"\nThe last element of the vector: {vector[-1]}")

Vektor: [1 2 3]
Matrix:
[[1 2 3]
 [4 5 6]]

Das 3. Element des Vektors: 3

Das 2. Element in der 2. Zeile der Matrix: 5

Alle Elemente bis und inklusive dem 2. Element des Vektors: [1 2]

Alles ab dem 3. Element des Vektors: []

Alle Elemente des Vektors: [1 2 3]

Das letzte Element des Vektors: 3


### Properties of a matrix

In [ ]:
matrix = np.array([[1,2,3],[4,5,6]])
print(f"Matrix:\n{matrix}")

# Anzahl von Reihen und Spalten
print(f"\nForm der Matrix (Anzahl von Reihen und Spalten): {matrix.shape}")

# Anzahl der Elemente (Reihen * Spalten)
print(f"\nAnzahl der Elemente (Reihen * Spalten): {matrix.size}")

# Anzahl der Dimensionen
print(f"\nDimension der Matrix: {matrix.ndim}")

Matrix:
[[1 2 3]
 [4 5 6]]

Form der Matrix (Anzahl von Reihen und Spalten): (2, 3)

Anzahl der Elemente (Reihen * Spalten): 6

Dimension der Matrix: 2


#### Transformationen auf Matrizen

Wie in der nächsten Zeile an einigen Beispielen gezeigt, lassen sich Numpy Arrays relativ einfach in eine andere Form (unterschidliches shape) verwandeln.

Hierbei muss ausschließlich darauf geachtet werden, dass die Elemente der neuen Form immernoch die gleiche Anzahl an Elementen besitzt wie die alte Form.

Die Matrix speichert die neue Form nicht, sondern dies muss mit einer neuen Variablenzuweisung geschehen.

`matrix.T` ist eine besondere Art der Umformung und spiegelt die Werte an der Diagonalen (Transponierte Matrix)

In [ ]:
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(f"Matrix:\n{matrix}")

print(f"\nReshaped (12x1):\n{matrix.reshape(12,1)}")

print(f"\nReshaped (1x12):\n{matrix.reshape(1,12)}")

print(f"\nReshaped (2x6):\n{matrix.reshape(2,6)}")

print(f"\nReshaped (1 Zeile mit so vielen Spalten wie nötig (-1)):\n{matrix.reshape(1,-1)}")

print(f"\nFlattened (Umwandlung in ein unverschachteltes 1D Array):\n{matrix.flatten()}")

print(f"\nTransponiert (Spiegelung an der Diagonalen):\n{matrix.T}")

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped (12x1):
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]

Reshaped (1x12):
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]

Reshaped (2x6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Reshaped (1 Zeile mit so vielen Spalten wie nötig (-1)):
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]

Flattened (Umwandlung in ein unverschachteltes 1D Array):
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Transponiert (Spiegelung an der Diagonalen):
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


#### Punktprodukt

Der dot-Operator (oder @) bildet das bekannte Punktprodukt von 2 Vektoren. 

In [ ]:
vector1 = np.array([1,2,3])
vector2 = np.array([1,1,1])
print(f"Vector1: {vector1}")
print(f"Vector2: {vector2}")

# Punktprodukt
print(f"\nPunktprodukt = {np.dot(vector1,vector2)}")

# Punktprodukt kann auch mit dem @ Operator geschrieben werden
# vector1 @ vector2

Vector1: [1 2 3]
Vector2: [1 1 1]

Punktprodukt = 6



#### Rechenoperationen von Matrizen

Die Elementbasierten Operationen funktionieren, wie der Name schon sagt auf den einzelnen Elementen. So wird das 1. Element der einen Matrix mit dem 1. Element der anderen Matrix verrechnet usw.

Die klassische Matrixmultiplikation funktioniert mit dem dot-Operator, welcher normalerweise das Punktprodukt von 2 Vektoren bildet.
Hierfür müssen die verrechneten Matrizen nur in die richtige Form gebracht werden, sodass die Spalten der ersten Matrix mit den Reihen der zweiten Matrix über einstimmen. 

In [ ]:
matrix1 = np.array([[1,2,3],[4,5,6]])
matrix2 = np.array([[2,2,2],[2,2,2]])
print(f"Matrix1:\n{matrix1}")
print(f"\nMatrix2:\n{matrix2}")

# Elementweise Addition
print(f"\nmatrix1 + matrix2 =\n{matrix1 + matrix2}")

# Elementweise Subtraktion
print(f"\nmatrix1 - matrix2 =\n{matrix1 - matrix2}")

# Elementweise Multiplikation
print(f"\nmatrix1 * matrix2 =\n{matrix1 * matrix2}")

# Elementweise Division
print(f"\nmatrix1 / matrix2 =\n{matrix1 / matrix2}")

# Matrixmultiplikation (nur möglich für (n x m)-Matrix * (m x l)-Matrix)
# Reshape muss vorgenommen werden
dot = np.dot(matrix1.reshape(3,2),matrix2)
print(f"\nMatrixmultiplikation =\n{dot}")

Matrix1:
[[1 2 3]
 [4 5 6]]

Matrix2:
[[2 2 2]
 [2 2 2]]

matrix1 + matrix2 =
[[3 4 5]
 [6 7 8]]

matrix1 - matrix2 =
[[-1  0  1]
 [ 2  3  4]]

matrix1 * matrix2 =
[[ 2  4  6]
 [ 8 10 12]]

matrix1 / matrix2 =
[[0.5 1.  1.5]
 [2.  2.5 3. ]]

Matrixmultiplikation =
[[ 6  6  6]
 [14 14 14]
 [22 22 22]]


#### Anwenden von Funktionen auf mehrere Elemente

Mit Hilfe des `lambda`-Operators können anonyme Funktionen, d.h. Funktionen ohne Namen erzeugt werden. Sie haben eine beliebige Anzahl von Parametern, führen einen Ausdruck aus und liefern den Wert dieses Ausdrucks als Rückgabewert zurück.

Bekommt die Funktion ein mehrdimensionales Numpy Array operiert es auf allen Elementen seperat. 

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Ein lambda Ausdruck der die Eingabe mit 100 addiert und implizit returned
add_100 = lambda i: i+100

# Funktionsanwendung auf alle Elemente der Matrix
matrix = add_100(matrix)
print(matrix)

[[101 102 103]
 [104 105 106]
 [107 108 109]]


#### Berechnen von Durchschnitt, Standardabweichung und Varianz

Numpy bietet ebenso einige statistische Funktionalitäten, welche für unsere Zwecke erstmal nicht von Relevanz sind. 

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Statistisches Mittel
print(np.mean(matrix))

# Standardabweichung
print(np.std(matrix))

# Varianz
print(np.var(matrix))

5.0
2.581988897471611
6.666666666666667


#### Berechnung von Zufallswerten

Wir wollen immer die gleiche pseudozufällige Folge an Werten erhalten, woraufhin wir den Zufallsgenerator "seeden".
Die mehrfache Ausführung der Zelle gibt somit die immer gleichen Elemente zurück, was ohne `np.random.seed(1)` nicht der Fall wäre. 

Versucht es gerne aus!!

In [ ]:
# Generator seeden um reproduzierbare Ausgaben zu erhalten
 np.random.seed(1)

# Generiert 3 zufällige Integer zwischen 0 und 10
print(np.random.randint(0,11,3))

# Generiert eine zufällige 2x2 Matrix
# Die Werte der Matrix sind floats einer Normalverteilung mit Mittelwert 0 und Varianz 1
print(np.random.randn(2, 2))

# 3 Zahlen aus einer Normalverteilung mit Mittelwert 1 und Varianz 2
print(np.random.normal(1.0, 2.0, 3))

[5 8 9]
[[-0.80217284 -0.44887781]
 [-1.10593508 -1.65451545]]
[-3.72693721  3.2706907  -1.03402827]


#### Datentyp ändern

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Ändert Datentyp der Elemente zu floats
print(matrix.astype(float))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


#### Arrays verketten

Mittels der `append()` Funktion lassen sich Vektoren mit einander verketten. Sollten die Arrays von einem unterschiedlichen Datentyp sein, werden die Werte in den größeren Datentyp konvertiert (z.B. int -> float -> strings)

In [ ]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

# Vektoren verketten
print(np.append(vector1, vector2))

# Alternativ concatenate
# np.concatenate((vector1, vector2))

[1 2 3 4 5 6]


#### Finden von Minimum und Maximum

Die Funktionen `min()` und `max()` sind in ihrer Bezeichnung recht eindeutig, wohingegen `argmax()` bzw `argmin()` für die Indizes dieser Elemente steht.

Durch die Angabe einer Achse werden die entsprechenden Elemente entlang dieser Achse beschrieben (mit 0 werden die maximalen Elemente in den Spalten und mit 1 die maximalen Elemente in den Reihen angegeben).

In [ ]:
matrix = np.array([[1,4,3],[34,7,6],[27,18,9]])
print(matrix)

# Maximales Element
print(f"\nMax: {np.max(matrix)}")

# Minimales Element
print(f"Min: {np.max(matrix)}")

# Die Indizes der maximalen Elemente entlang einer Achse
print(f"Indizes der maximalen Elemente aus Achse 0: {np.argmax(matrix, axis=0)}")

# Das maximale Element entlang einer Achse zurückgeben
print(f"Maximale Elemente der Achse 0: {np.max(matrix,axis=0)}")

[[ 1  4  3]
 [34  7  6]
 [27 18  9]]

Max: 34
Min: 34
Indizes der maximalen Elemente aus Achse 0: [1 2 2]
Maximale Elemente der Achse 0: [34 18  9]


#### Matrixdiagonale, Spur

Auch auf diese Funktionalitäten wollten wir nicht weiter eingehen, da sie für unsere Zwecke keine große Bedeutung haben. Sie sind hier eher der vollständigkeitshalber mit aufgeführt. 

In [ ]:
matrix = np.array([[1,4,3],[34,7,6],[27,18,9]])
print(matrix)

# Hauptdiagonale
print(f"\nHauptdiagonale: {matrix.diagonal()}")

# Diagonale direkt über der Hauptdiagonalen
print(f"Diagonale über der Hauptdiagonalen: {matrix.diagonal(offset=1)}")

# Spur der Matrix (Summe der Elemente der Hauptdiagonalen)
print(f"Spur: {matrix.trace()}")

[[ 1  4  3]
 [34  7  6]
 [27 18  9]]

Hauptdiagonale: [1 7 9]
Diagonale über der Hauptdiagonalen: [4 6]
Spur: 17
