<a href="https://colab.research.google.com/github/schmelto/machine-learning/blob/main/Deeplearning/introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Numpy


## Import Numpy

Before we can use the full functionality of NumPy, we first have to import the library. With the abbreviation "as" we give numpy a "nickname" and from now on we can write np.some_function () for all functions of Numpy.

In [1]:
import numpy as np

## Numpy functionalities

### Create a vector

A vector in Numpy is represented as an array. Here, a horizontal vector is a 1-dimensional and a vertical vector is a 2-dimensional vector.

The function `np.array ()` creates this multidimensional numpy array (ndarray).

In [2]:
vector_row = np.array([1,2,3]) # Horizontal vector (1D)
vector_column = np.array([[1],[2],[3]]) # Vertical vector (2D and thus n x 1 matrix)
print(vector_row)
print(vector_column)

[1 2 3]
[[1]
 [2]
 [3]]


### Create a matrix

A matrix is also a multi-dimensional array.

Here, too, this is generated with the `np.array ()` function, whereby the number of nestings (array in an array) represents the dimension of the matrix.

In [3]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


### Helpful initializations of an array

The arrays can be easily filled with data using a few functions.

Here `np.arrange ()` and `np.linspace ()` offer different approaches to create an array with a specific interval.

In [4]:
# Values from 0 to 30 (exclusive) with step size 2
range_with_fixed_interval = np.arange(0, 30, 2)
print(f"Vektor with arange:\n{range_with_fixed_interval} \n")

# 9 evenly distributed values between 0 and 4
equally_spaced_range = np.linspace(0, 4, 9)
print(f"Vektor with linspace:\n{equally_spaced_range} \n")

Vektor with arange:
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28] 

Vektor with linspace:
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ] 



### Helpful initializations of a matrix

There are also clearly defined functions for creating special matrices.

An identity matrix or a matrix of any size, which consists exclusively of ones or zeros, can be created very easily.

In [5]:
matrix_id = np.eye(3)           # 3 x 3 identity matrix
matrix_ones = np.ones((3, 2))   # Matrix of ones
matrix_zeros = np.zeros((3, 2)) # Matrix of zeros
print(f"identity matrix:\n{matrix_id} \n")
print(f"Ones matrix:\n{matrix_ones} \n")
print(f"Zeros matrix:\n{matrix_zeros} \n")

identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Ones matrix:
[[1. 1.]
 [1. 1.]
 [1. 1.]] 

Zeros matrix:
[[0. 0.]
 [0. 0.]
 [0. 0.]] 



#### Access to elements of a multi-dimensional array

Access to the individual elements works as shown below and is probably also known from other programming languages.

Using the :-notation, a certain area of the array can be easily queried by specifying a start and end index.
In the case of the index with negative numbers, the array goes through its values in the reverse order.

In [6]:
vector = np.array([1,2,3])
matrix = np.array([[1,2,3],[4,5,6]])
print(f"Vektor: {vector}")
print(f"Matrix:\n{matrix}")

# The 3rd element of the vector
print(f"\nThe 3rd element of the vector: {vector[2]}")

# The 2nd element in the 2nd row of the matrix
print(f"\nThe 2nd element in the 2nd row of the matrix: {matrix[1,1]}")

# All elements up to and including the 2nd element
print(f"\nAll elements up to and including the 2nd element of the vector: {vector[:2]}")

# Everything from the 3rd element
print(f"\nEverything from the 3rd element of the vector: {vector[3:]}")

# All elements of the vector
print(f"\nAll elements of the vector: {vector[:]}")

# The last element (same result as vector [len (vector) -1])
print(f"\nThe last element of the vector: {vector[-1]}")

Vektor: [1 2 3]
Matrix:
[[1 2 3]
 [4 5 6]]

The 3rd element of the vector: 3

The 2nd element in the 2nd row of the matrix: 5

All elements up to and including the 2nd element of the vector: [1 2]

Everything from the 3rd element of the vector: []

All elements of the vector: [1 2 3]

The last element of the vector: 3


### Properties of a matrix

In [7]:
matrix = np.array([[1,2,3],[4,5,6]])
print(f"Matrix:\n{matrix}")

# Number of rows and columns
print(f"\nShape of the matrix (number of rows and columns): {matrix.shape}")

# Number of elements (rows * columns)
print(f"\nNumber of elements (rows * columns): {matrix.size}")

# Number of dimensions
print(f"\nDimension of the matrix: {matrix.ndim}")

Matrix:
[[1 2 3]
 [4 5 6]]

Shape of the matrix (number of rows and columns): (2, 3)

Number of elements (rows * columns): 6

Dimension of the matrix: 2


### Transformations on matrices

As shown in some examples in the next line, numpy arrays can be transformed into a different shape (different shape) relatively easily.

The only thing that has to be ensured here is that the elements of the new form still have the same number of elements as the old form.

The matrix does not save the new form, it must be done with a new variable assignment.

`matrix.T` is a special type of transformation and reflects the values on the diagonal (transposed matrix)

In [8]:
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(f"Matrix:\n{matrix}")

print(f"\nReshaped (12x1):\n{matrix.reshape(12,1)}")

print(f"\nReshaped (1x12):\n{matrix.reshape(1,12)}")

print(f"\nReshaped (2x6):\n{matrix.reshape(2,6)}")

print(f"\nReshaped (1 row with as many columns as necessary (-1)):\n{matrix.reshape(1,-1)}")

print(f"\nFlattened (Conversion to a non-nested 1D array):\n{matrix.flatten()}")

print(f"\nTransponiert (Reflection on the diagonal):\n{matrix.T}")

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped (12x1):
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]

Reshaped (1x12):
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]

Reshaped (2x6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Reshaped (1 row with as many columns as necessary (-1)):
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]

Flattened (Conversion to a non-nested 1D array):
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Transponiert (Reflection on the diagonal):
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### Dot product

The dot operator (or @) forms the well-known dot product of 2 vectors.

In [9]:
vector1 = np.array([1,2,3])
vector2 = np.array([1,1,1])
print(f"Vector1: {vector1}")
print(f"Vector2: {vector2}")

# Dot product
print(f"\nDot product = {np.dot(vector1,vector2)}")

# Dot product can also be written with the @ operator
# vector1 @ vector2

Vector1: [1 2 3]
Vector2: [1 1 1]

Dot product = 6


### Arithmetic operations of matrices

The element-based operations work, as the name suggests, on the individual elements. The 1st element of one matrix is offset against the 1st element of the other matrix, etc.

The classic matrix multiplication works with the dot operator, which normally forms the dot product of 2 vectors.
To do this, the calculated matrices only have to be brought into the correct form so that the columns of the first matrix match the rows of the second matrix.

In [10]:
matrix1 = np.array([[1,2,3],[4,5,6]])
matrix2 = np.array([[2,2,2],[2,2,2]])
print(f"Matrix1:\n{matrix1}")
print(f"\nMatrix2:\n{matrix2}")

# Addition by element
print(f"\nmatrix1 + matrix2 =\n{matrix1 + matrix2}")

# Subtraction by element
print(f"\nmatrix1 - matrix2 =\n{matrix1 - matrix2}")

# Multiplication by element
print(f"\nmatrix1 * matrix2 =\n{matrix1 * matrix2}")

# Division by element
print(f"\nmatrix1 / matrix2 =\n{matrix1 / matrix2}")

# Matrix multiplication (only possible for (n x m) matrix * (m x l) matrix)
# Reshape needs to be done
dot = np.dot(matrix1.reshape(3,2),matrix2)
print(f"\nMatrix multiplication =\n{dot}")

Matrix1:
[[1 2 3]
 [4 5 6]]

Matrix2:
[[2 2 2]
 [2 2 2]]

matrix1 + matrix2 =
[[3 4 5]
 [6 7 8]]

matrix1 - matrix2 =
[[-1  0  1]
 [ 2  3  4]]

matrix1 * matrix2 =
[[ 2  4  6]
 [ 8 10 12]]

matrix1 / matrix2 =
[[0.5 1.  1.5]
 [2.  2.5 3. ]]

Matrix multiplication =
[[ 6  6  6]
 [14 14 14]
 [22 22 22]]


### Applying functions to multiple elements

With the help of the `lambda` operator, anonymous functions, i.e. Functions without names are created. You can have any number of parameters, execute an expression, and return the value of this expression as a return value.

If the function receives a multidimensional numpy array, it operates on all elements separately.

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

# A lambda expression that adds the input to 100 and implicitly returned
add_100 = lambda i: i+100

# Function application to all elements of the matrix
matrix = add_100(matrix)
print(matrix)

[[101 102 103]
 [104 105 106]
 [107 108 109]]


### Calculate mean, standard deviation, and variance

Numpy also offers some statistical functions, which are initially not relevant for our purposes.

In [11]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Statistical mean
print(np.mean(matrix))

# Standard deviation
print(np.std(matrix))

# Variance
print(np.var(matrix))

5.0
2.581988897471611
6.666666666666667


### Calculation of random values

We always want to receive the same pseudo-random sequence of values, whereupon we "seed" the random number generator.
Executing the cell multiple times therefore always returns the same elements, which would not be the case without `np.random.seed (1)`.

In [13]:
# Seed the generator to get reproducible output
np.random.seed(1)

# Generates 3 random integers between 0 and 10
print(np.random.randint(0,11,3))

# Generates a random 2x2 matrix
# The values of the matrix are floats of a normal distribution with mean 0 and variance 1
print(np.random.randn(2, 2))

# 3 Numbers from a normal distribution with mean 1 and variance 2
print(np.random.normal(1.0, 2.0, 3))

[5 8 9]
[[-0.80217284 -0.44887781]
 [-1.10593508 -1.65451545]]
[-3.72693721  3.2706907  -1.03402827]


### Change data type

In [14]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Changes the data type of the elements to floats
print(matrix.astype(float))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Concatenate arrays

Using the `append ()` function, vectors can be linked together. If the arrays are of a different data type, the values are converted to the larger data type (e.g. int -> float -> strings)

In [ ]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

# Concatenate arrays
print(np.append(vector1, vector2))

# Alternativ concatenate
# np.concatenate((vector1, vector2))

[1 2 3 4 5 6]


### Finding minimum and maximum

The names of the functions `min ()` and `max ()` are very clear, whereas `argmax ()` and `argmin ()` stand for the indices of these elements.

By specifying an axis, the corresponding elements are described along this axis (with 0 the maximum elements in the columns and with 1 the maximum elements in the rows).

In [15]:
matrix = np.array([[1,4,3],[34,7,6],[27,18,9]])
print(matrix)

# Maximum element
print(f"\nMax: {np.max(matrix)}")

# Minimal element
print(f"Min: {np.max(matrix)}")

# The indexes of the maximum elements along an axis
print(f"Indexes of the maximum elements from axis 0: {np.argmax(matrix, axis=0)}")

# Return the maximum element along an axis
print(f"Maximum elements of axis 0: {np.max(matrix,axis=0)}")

[[ 1  4  3]
 [34  7  6]
 [27 18  9]]

Max: 34
Min: 34
Indexes of the maximum elements from axis 0: [1 2 2]
Maximum elements of axis 0: [34 18  9]


### matrix diagonal, trace

In [16]:
matrix = np.array([[1,4,3],[34,7,6],[27,18,9]])
print(matrix)

# Main diagonal
print(f"\nMain diagonal: {matrix.diagonal()}")

# Diagonal above the main diagonal
print(f"Diagonal above the main diagonal: {matrix.diagonal(offset=1)}")

# Trace of the matrix (sum of the elements of the main diagonal)
print(f"Trace: {matrix.trace()}")

[[ 1  4  3]
 [34  7  6]
 [27 18  9]]

Main diagonal: [1 7 9]
Diagonal above the main diagonal: [4 6]
Trace: 17
